version: '3'
services:

  drawio:
    image: jgraph/drawio:14.5.1
    environment:
      - TZ=Asia/Seoul
    ports:
      - '8080:8080'
      - '8443:8443'

  jekyll:
    image: jekyll/jekyll:4
    command: bundle install && bundle exec jekyll serve --host 0.0.0.0 --draft --watch
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - '4000:4000'